chaostreffs = [
  {
    slug: "chaostreff-aalen",
    title_de: "Chaostreff Aalen",
    title_en: nil,
    description_de: "Wir sind ein Chaostreff und Hackspace in Aalen im Aaccellerator, Blezingerstraße 15, 73430 Aalen. Wir treffen uns regelmäßig jeden 3. Dienstag im Monat ab 18:30 Uhr. Für Treffen außerhalb von den Regelterminen verabreden wir uns spontan über <a href=\"https://matrix.to/#/#makerspace-aalen:famhahn.xyz\">Matrix</a>.",
    description_en: nil,
    external_url: "https://aalen.space/",
    location: "Blezingerstraße 15, 73430 Aalen",
    rrule: "FREQ=MONTHLY;BYDAY=3TU",
    start_time: "18:30",
    review: false
  },
  {
    slug: "chaostreff-alzey",
    title_de: "Chaostreff Alzey",
    title_en: nil,
    description_de: "An jedem ersten Sonntag des Monats trifft sich der Chaostreff Alzey um 15 Uhr im Juku Alzey. All creatures welcome!",
    description_en: nil,
    external_url: "https://chaostreff-alzey.de/",
    location: "Juku Alzey",
    rrule: "FREQ=MONTHLY;BYDAY=1SU",
    start_time: "15:00",
    review: false
  },
  {
    slug: "chaostreff-amberg-sulzbach",
    title_de: "Chaostreff Amberg-Sulzbach",
    title_en: nil,
    description_de: "Wir treffen uns monatlich in Amberg in lockerer Runde. Es wird keine Anmeldung benötigt. All Creatures Welcome! Ort und Zeit der Treffen findet ihr auf der Webseite des Chaostreffs.",
    description_en: nil,
    external_url: "https://amborg-sulzbyte.de/",
    location: "Amberg",
    rrule: "FREQ=MONTHLY",
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-amsterdam",
    title_de: "Chaos Amsterdam",
    title_en: "Chaos Amsterdam",
    description_de: "Chaos Amsterdam meets on Thursdays every other week at 19:00 in a social space close to the city center. We can be found on <a href=\"https://webirc.hackint.org/#chaosamsterdam\">IRC in #chaosamsterdam</a> on the hackint network.",
    description_en: "Chaos Amsterdam meets on Thursdays every other week at 19:00 in a social space close to the city center. We can be found on <a href=\"https://webirc.hackint.org/#chaosamsterdam\">IRC in #chaosamsterdam</a> on the hackint network.",
    external_url: "https://chaos.amsterdam/",
    location: "Amsterdam",
    rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-andernach",
    title_de: "haxko e.V. Andernach",
    title_en: nil,
    description_de: "Der Hacker- und Makerspace Mayen-Koblenz (haxko e.V.) befindet sich in der ehemaligen Gastwirtschaft des Bahnhofs Andernach. Unsere Treffen finden in geraden Kalenderwochen freitags und in ungeraden samstags statt. Beginn immer ab 18 Uhr. Thematisch sind wir offen und durch die Location direkt am Bahnhof gut zu erreichen.",
    description_en: nil,
    external_url: "https://haxko.space",
    location: "Bahnhof Andernach",
    rrule: "FREQ=WEEKLY;BYDAY=FR",
    start_time: "18:00",
    review: false
  },
  {
    slug: "chaostreff-augsburg",
    title_de: "OpenLab Augsburg",
    title_en: nil,
    description_de: "Aus dem <a href=\"https://c3a.de\">Chaostreff Augsburg</a> entstanden ist das <a href=\"https://openlab-augsburg.de\">OpenLab</a> heute der Anlaufpunkt für alle die an nachhaltigem Handeln &amp; Herstellen, dem kreativem Umgang mit Technik, Datenschutz und digitaler Selbstbemächtigung interessiert sind. Jeden Donnerstag offen für Interessierte und jeden dritten Donnerstag auch mit Vortrag im bekannten Chaostreff-Stil.",
    description_en: nil,
    external_url: "https://openlab-augsburg.de",
    location: "Augsburg",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-aschaffenburg",
    title_de: "Makerspace Schaffenburg",
    title_en: nil,
    description_de: "Der Chaostreff im Makerspace Schaffenburg ist ein Zusammenschluss von technikbegeisterten Menschen, die zusammen in (A)schaffenburg einen Ort schaffen, der genau dies bietet: Platz und Werkzeug zum Arbeiten, motivierte Menschen mit Know-How, kreative Ideen und Inspiration. Kurz gesagt: Raum für alle, die etwas machen wollen – ein Makerspace! Zu finden sind wir in der Dorfstraße 1 in Aschaffenburg.",
    description_en: nil,
    external_url: "http://www.schaffenburg.org",
    location: "Dorfstraße 1, Aschaffenburg",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-backnang",
    title_de: "Chaostreff Backnang",
    title_en: nil,
    description_de: "Wir treffen uns an jedem 3. Sonntag des Monats zum Erfahrungsaustausch und der gemeinsamen Umsetzung von Projekten sowie an jedem 1. Dienstag im Monat zum offenen Stammtisch im dasWohnzimmer (Willy-Brandt-Platz 2) in Backnang bei Stuttgart und freuen uns auf neue Gesichter. Strom, Freifunk sowie Getränke und Snacks der Bar (auch Mate) werden angeboten.",
    description_en: nil,
    external_url: "https://chaostreff-backnang.de/",
    location: "Willy-Brandt-Platz 2, Backnang",
    rrule: "FREQ=MONTHLY;BYDAY=3SU",
    start_time: "18:00",
    review: false
  },
  {
    slug: "chaostreff-bayreuth",
    title_de: "Imaginärraum Bayreuth",
    title_en: nil,
    description_de: "Der Imaginärraum ist ein junger Hackerspace, der sich jeden Montag um 19 Uhr in seinen Räumen in der Schulstraße 7 in Bayreuth trifft.",
    description_en: nil,
    external_url: "https://imaginaerraum.de/",
    location: "Schulstraße 7, Bayreuth",
    rrule: "FREQ=WEEKLY;BYDAY=MO",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-bern",
    title_de: "Chaostreff Bern",
    title_en: nil,
    description_de: "Der Chaostreff Bern trifft sich jeden Dienstag ab 19 Uhr im eigenen Hackerspace an der Zwyssigstrasse 45. Dort gibt es Strom, Internet, Mate und viel Platz zum Hacken.",
    description_en: nil,
    external_url: "https://www.chaostreffbern.ch/",
    location: "Zwyssigstrasse 45, Bern",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-bielefeld",
    title_de: "Hackerspace Bielefeld",
    title_en: nil,
    description_de: "Bielefeld gibt's gar nicht? Weiß man nicht. Gibt es denn einen Chaostreff? Auch das ist ungewiss, aber chaosnahe Leute treffen sich im <a href=\"http://hackerspace-bielefeld.de/\">Hackerspace Bielefeld</a>.",
    description_en: nil,
    external_url: "http://hackerspace-bielefeld.de/",
    location: "Bielefeld",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-bingen",
    title_de: "/bin/hacken Bingen",
    title_en: nil,
    description_de: "Seit Anfang 2019 sind wir /bin/hacken, ein Hacker- &amp; Makerspace in Bingen am Rhein. Wir bieten wöchentliche Treffen und eine offene Werkstatt zum Mitgestalten oder einfach eigene Projekte verwirklichen!",
    description_en: nil,
    external_url: "https://binhacken.de/",
    location: "Bingen am Rhein",
    rrule: "FREQ=WEEKLY",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-bochum",
    title_de: "Das Labor Bochum",
    title_en: nil,
    description_de: "Das Labor, Hackspace und Chaostreff, ist in erster Linie ein Ort, an dem praktisch gearbeitet wird. Wir benutzen und entwickeln freie Software, löten, ätzen und programmieren Mikrocontroller, beschäftigen uns mit 3D-Druck, Freifunk, Amateurfunk, IT-Sicherheit, Arduinos, OSM oder Open Science. Wir haben den Anspruch, mit Technologie Neues und Sinnvolles zu erschaffen. Im Labor gibt es Vorträge, Workshops und Diskussionen zu den unterschiedlichsten Bereichen der Technik.",
    description_en: nil,
    external_url: "https://das-labor.org",
    location: "Bochum",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-bonn",
    title_de: "Datenburg e.V. Bonn",
    title_en: nil,
    description_de: "Der Datenburg e.V. ist ein seit 2019 existierender Hackspace und Chaostreff in Bonn und seit Anfang 2024 ein eingetragener Verein. Wir beschäftigen uns mit Themen rund um Technik und Gesellschaft. Die Datenburg ist auch ein Ort, um an eigenen Projekten zu arbeiten und sich auszutauschen. Wir öffnen jeden Dienstag ab 20 Uhr unsere Tore für alle interessierten Wesen.",
    description_en: nil,
    external_url: "https://datenburg.org/",
    location: "Bonn",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "20:00",
    review: false
  },
  {
    slug: "chaostreff-budapest",
    title_de: "H.A.C.K. Budapest",
    title_en: "H.A.C.K. Budapest",
    description_de: "Members of the Hungarian Autonomous Center for Knowledge (H.A.C.K.) usually meet on Tuesdays at 19:00 local time, but it's best to confirm beforehand on #hspbp at IRCnet. We're located in the middle of the city, and we have Mate, sticker exchange, Internet, and friendly hackers.",
    description_en: "Members of the Hungarian Autonomous Center for Knowledge (H.A.C.K.) usually meet on Tuesdays at 19:00 local time, but it's best to confirm beforehand on #hspbp at IRCnet. We're located in the middle of the city, and we have Mate, sticker exchange, Internet, and friendly hackers.",
    external_url: "https://hsbp.org/contact-us",
    location: "Budapest",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-coburg",
    title_de: "Hackzogtum Coburg",
    title_en: nil,
    description_de: "Coburgs Chaostreff/Hackspace ist das Hackzogtum Coburg. Bei uns stehen vor allem Spaß an der Technik und reger Austausch im Vordergrund. Wer vorbeischauen will, ist bei uns immer willkommen. Ihr findet uns physikalisch in der Heiligkreuzstr. 3 in 96450 Coburg. Die meisten Leute gleichzeitig treffen sich immer dienstags ab 20 Uhr.",
    description_en: nil,
    external_url: "https://hackzogtum-coburg.de",
    location: "Heiligkreuzstr. 3, 96450 Coburg",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "20:00",
    review: false
  },
  {
    slug: "chaostreff-cottbus",
    title_de: "Chaostreff Cottbus",
    title_en: nil,
    description_de: "Der Treff für alle Chaos-Interessierten aus Cottbus und Umgebung. Angesiedelt am FabLab Cottbus (Walther-Pauer-Straße 7), treffen wir uns regelmäßig am letzten Mittwoch im Monat ab 18 Uhr und freuen uns auf neue Gesichter.",
    description_en: nil,
    external_url: "https://chaos-cb.de",
    location: "Walther-Pauer-Straße 7, Cottbus",
    rrule: "FREQ=MONTHLY;BYDAY=-1WE",
    start_time: "18:00",
    review: false
  },
  {
    slug: "chaostreff-eisenach",
    title_de: "WAK-Lab Eisenach",
    title_en: nil,
    description_de: "Das <a href=\"https://wak-lab.org\">WAK-Lab</a> ist ein Raum für Hacker, Bastler und technikinteressierte Menschen. Unsere Ziele sind der Aufbau einer offenen Werkstatt, um den Erwerb und das Teilen von technischem Wissen zu fördern. Kontakt über <a href=\"https://matrix.to/#/#wak-lab:im.kabi.tk\">Matrix</a> oder auf unserer Homepage.",
    description_en: nil,
    external_url: "https://wak-lab.org",
    location: "Eisenach",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-erfurt",
    title_de: "Bytespeicher Erfurt",
    title_en: nil,
    description_de: "Der Hackspace Bytespeicher öffnet jeden Mittwoch zum Open Space und trifft sich ab 19 Uhr zum Chaostreff Erfurt in der Liebknechtstraße 8. Wir bieten mit Hackspace, Konferenzraum und Elektronikwerkstatt alle Möglichkeiten zum gemeinsamen Hacken, Lernen, Präsentieren und Experimentieren. Wir unterstützen außerdem Freifunk Erfurt und die Programmier-Initiative Kids@Digital.",
    description_en: nil,
    external_url: "https://www.bytespeicher.org/",
    location: "Liebknechtstraße 8, Erfurt",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-giessen",
    title_de: "Chaostreff Gießen",
    title_en: nil,
    description_de: "Lockerer Treff für alle Chaos-Interessierten aus dem Raum Gießen. Zur Zeit beherbergt uns am ersten Mittwoch des Monats das <a href=\"https://jhrings.de/\">Jhrings Wirtsstuben</a> (Ludwigstraße 10) ab 19 Uhr. An den anderen Mittwochen des Monats treffen wir uns in den Räumlichkeiten von <a href=\"https://mudbyte.de/\">Mudbytes</a>. Um Verwechslungen vorzubeugen, schaut bitte unter <a href=\"https://giessen.ccc.de\">giessen.ccc.de</a> nach dem aktuellen Stand.",
    description_en: nil,
    external_url: "https://giessen.ccc.de",
    location: "Ludwigstraße 10, Gießen",
    rrule: "FREQ=MONTHLY;BYDAY=1WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-graz",
    title_de: "RealRaum Graz",
    title_en: nil,
    description_de: "Grundsätzlich ist bei den Workshops und sonstigen Veranstaltungen immer jeder willkommen, der Lust hat, was Neues dazuzulernen oder selbst was dazu beizutragen, egal ob Mitglied oder nicht. Ziel ist es, einen chaotisch gemischten Haufen zu schaffen, der fähig ist, sich mit seinen Ideen gegenseitig zu inspirieren. Besonders sind alle willkommen, die bereits bei anderen Vereinen/Initiativen tätig sind (LUGG, STG, Spektral und ähnliches). Die Treffen finden im RealRaum statt.",
    description_en: nil,
    external_url: "https://realraum.at/",
    location: "Graz",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-goeppingen",
    title_de: "Chaostreff Göppingen (SCHAFFEREI)",
    title_en: nil,
    description_de: "Spaß an der Technik haben, kreativ sein, Altes reparieren, Neues generieren, Wissen teilen – gemeinsam macht das Chaos Laune. Der Chaostreff Göppingen findet monatlich in der Göppinger SCHAFFEREI statt. Freifunk, Lötkolben und Mate sind vorhanden.",
    description_en: nil,
    external_url: "https://schafferei.org/chaos-treff/",
    location: "Göppingen",
    rrule: "FREQ=MONTHLY",
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-gunzenhausen",
    title_de: "Chaostreff Gunzenhausen",
    title_en: nil,
    description_de: "Jeden Dienstag in einer ungeraden Kalenderwoche treffen wir uns ab 19 Uhr im <a href=\"https://fablab-altmuehlfranken.de\">FabLab in Gunzenhausen</a>. Gäste und Interessierte sind gerne willkommen!",
    description_en: nil,
    external_url: "https://chaostreff-gun.de/",
    location: "FabLab Gunzenhausen",
    rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-halle",
    title_de: "Chaostreff Halle (Saale)",
    title_en: nil,
    description_de: "Der Chaostreff trifft sich wöchentlich am Dienstag ab 19 Uhr im <a href=\"https://eigenbaukombinat.de\">Eigenbaukombinat</a> zum Hackerspacetreffen in der Landsberger Straße 3. Reden, tüfteln, hacken inklusive.",
    description_en: nil,
    external_url: "https://eigenbaukombinat.de",
    location: "Landsberger Straße 3, Halle (Saale)",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-hamm",
    title_de: "c3hamm",
    title_en: nil,
    description_de: "Wir, c3hamm, sind seit dem 5.5.2025 Verein. Bauen gerade am HHiC, ein Hackspace &amp; Repair-Cafe zum Mitnehmen im Container. Wir treffen uns regelmässig am 1ten Mittwoch im Monat im Rahmen des eStatischH (Energier-Stammtisch Hamm) VorOrt. Nicht selten treffen wir uns Sonntags zum VRunch inner Brille und erkunden SocialVR Räume, pflegen ein kleines cHaoS-Log: <a href=\"https://y.lab.nrw/c3h-logs\">y.lab.nrw/c3h-logs</a>.",
    description_en: nil,
    external_url: "https://chaos.social/@c3hamm",
    location: "Hamm",
    rrule: "FREQ=MONTHLY;BYDAY=1WE",
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-heidelberg",
    title_de: "NoName e.V. Heidelberg",
    title_en: nil,
    description_de: "Wir sind der NoName e.V., ein lustiger zusammengewürfelter Haufen, der sich mindestens einmal pro Woche trifft. Jeder Technikinteressierte ist bei uns gerne gesehen. Der regelmäßige Treff am Donnerstag findet abwechselnd an verschiedenen Orten statt. Infos über spontane Treffen findet man im TWiCEiRC-Channel #chaos-hd.",
    description_en: nil,
    external_url: "https://www.noname-ev.de",
    location: "Heidelberg",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-hildesheim",
    title_de: "Freies Labor Hildesheim",
    title_en: nil,
    description_de: "Der Hackerspace „Freies Labor" ist ein Ort, an dem sich unterschiedliche Disziplinen treffen, kennenlernen und kooperieren. In unserem Labor wollen wir in gemütlicher Atmosphäre gemeinsam tüfteln, kochen, brauen und entdecken. Wir wollen unsere Fähigkeiten und unser Wissen miteinander teilen und stellen Werkstatt, Küche und gemütliche Räume zur Verfügung.",
    description_en: nil,
    external_url: "https://blog.freieslabor.org/",
    location: "Hildesheim",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-hilpoltstein",
    title_de: "Chaostreff Hip Hilpoltstein",
    title_en: nil,
    description_de: "Jeden zweiten Dienstag (ungerade Kalenderwochen) trifft sich der Chaostreff Hip ab 18 Uhr zum gemeinsamen Tüfteln, Reden und Verkosten von Mate im Haus des Gastes (Maria-Dorothea-Straße 8). Interessierte Gäste sind immer herzlich willkommen.",
    description_en: nil,
    external_url: "https://chaos-hip.de/",
    location: "Maria-Dorothea-Straße 8, Hilpoltstein",
    rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=TU",
    start_time: "18:00",
    review: false
  },
  {
    slug: "chaostreff-hoher-flaeming",
    title_de: "ge.hackt.es Hoher Fläming",
    title_en: nil,
    description_de: "In Brandenburg, mitten im Wald, gibt es <a href=\"https://ge.hackt.es/\">ge.hackt.es</a>! In unserem Hackspace im Hohen Fläming beschäftigen wir uns nicht ganz zufällig mit Digitalisierung im ländlichen Raum. Wir basteln außerdem Schönes mit Sensoren und bringen ein Repair-Café an den Start. Schreibt uns, wenn ihr den Weg durch den Wald zu uns finden wollt!",
    description_en: nil,
    external_url: "https://ge.hackt.es/",
    location: "Hoher Fläming, Brandenburg",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-ilmenau",
    title_de: "ilmspace Ilmenau",
    title_en: nil,
    description_de: "Wir treffen uns regelmäßig jeden Mittwoch ab 19 Uhr zum <em>open space</em> und einmal im Monat zum Orgatreff. Der Space bietet Raum für alle Chaos-Interessierten aus Ilmenau und Umgebung. Wir helfen euch gern bei Reparaturen, beim Einstieg oder Umstieg in die Linuxwelt oder bei eigenen Projekten. Ihr seid herzlich eingeladen, aktiv unseren Space mitzugestalten. Kontakt via <a href=\"https://matrix.to/#/#SPACE:bau-ha.us\">Matrix</a>.",
    description_en: nil,
    external_url: "http://ilmspace.de/",
    location: "Ilmenau",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-ingolstadt",
    title_de: "bytewerk Ingolstadt",
    title_en: nil,
    description_de: "Am 10. April 2010 wurde in Ingolstadt das <a href=\"http://www.bytewerk.org/\">bytewerk</a> eröffnet, der Hackerspace des Ingolstädter Chaostreff, der aus dem <a href=\"http://www.bingo-ev.de/\">bingo e.V.</a> hervorgegangen ist.",
    description_en: nil,
    external_url: "http://www.bytewerk.org/",
    location: "Ingolstadt",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-innsbruck",
    title_de: "IT-Syndikat Innsbruck",
    title_en: nil,
    description_de: "Das chaosnahe IT-Syndikat ist (mindestens) jeden Dienstag ab 19 Uhr für Besuch offen. Wo? Tschamlerstraße 3, über dem Weekender Club. Sollte unten ein Türsteher-NPC den Weg versperren, kommt man mit einem Verweis auf „die Künstler/Hacker" immer vorbei.",
    description_en: nil,
    external_url: "http://it-syndikat.org",
    location: "Tschamlerstraße 3, Innsbruck",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-itzehoe",
    title_de: "Computerclub Itzehoe e.V.",
    title_en: nil,
    description_de: "Der Itzehoer Chaostreff ist beim Computerclub Itzehoe e.V. angesiedelt und beschäftigt sich zwanglos mit unterschiedlichsten Hard- und Softwareprojekten. Treffen sind donnerstags ab 19 Uhr.",
    description_en: nil,
    external_url: "http://cciz.de/",
    location: "Itzehoe",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-jena",
    title_de: "Offener Chaostreff Jena (Krautspace)",
    title_en: nil,
    description_de: "Der Offene Chaostreff Jena trifft sich dienstags ab 20 Uhr im Krautspace in der Krautgasse 26.",
    description_en: nil,
    external_url: "https://kraut.space/",
    location: "Krautgasse 26, Jena",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "20:00",
    review: false
  },
  {
    slug: "chaostreff-kiel",
    title_de: "Science Monday Kiel (Toppoint)",
    title_en: nil,
    description_de: "<em>Science Monday - Chaos and more</em> ist der lokale Chaostreff in Kiel. Seit dem ersten Chaostreffen in Kiel finden die Treffen montags ab 19 Uhr in den Räumen der Toppoint statt.",
    description_en: nil,
    external_url: "http://toppoint.de/",
    location: "Kiel",
    rrule: "FREQ=WEEKLY;BYDAY=MO",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-klaus-vorarlberg",
    title_de: "Open-Lab Klaus (Vorarlberg)",
    title_en: nil,
    description_de: "Wir treffen uns jeden Dienstag von 16-20 Uhr im <a href=\"https://open-lab.at/index.php/info/location\">Open-Lab</a> in Klaus, Vorarlberg. Ob jung, ob alt, es ist jewesen bei uns willkommen. Wir haben Internet, Werkzeuge, Lötkolben, 3D-Drucker, Sofas und noch einiges mehr zur Verfügung.",
    description_en: nil,
    external_url: "https://open-lab.at/",
    location: "Klaus, Vorarlberg",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "16:00",
    review: false
  },
  {
    slug: "chaostreff-konstanz",
    title_de: "hacKNology e.V. Konstanz",
    title_en: nil,
    description_de: "Der Chaostreff Konstanz trifft sich jeden 2. Dienstag um 19 Uhr in den Räumlichkeiten des Hackerspace hacKNology e. V.",
    description_en: nil,
    external_url: "https://www.hacknology.de/",
    location: "Konstanz",
    rrule: "FREQ=MONTHLY;BYDAY=2TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-landau",
    title_de: "CTRL-Z Landau",
    title_en: nil,
    description_de: "<a href=\"https://ctrl-z.info/\">CTRL-Z</a> lädt an drei Dienstagen im Monat zum Open Space bis 23 Uhr ein. Als Teil des <a href=\"https://ztl.space/\">Zentrums für Technikkultur Landau e. V.</a> kann man uns auch bei den zahlreichen Workshops im ZTL treffen. Wir hoffen, ihr schaut mal bei uns vorbei, in der Klaus-Von-Klitzing-Str. 2, im schönen Landau in der Pfalz. Unser Zugang ist barrierefrei, all creatures welcome!",
    description_en: nil,
    external_url: "https://ctrl-z.info/",
    location: "Klaus-Von-Klitzing-Str. 2, Landau",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-loerrach",
    title_de: "technik.cafe Lörrach",
    title_en: nil,
    description_de: "Im technik.cafe Lörrach trifft sich monatlich der Chaostreff Lörrach. Dort wird gefachsimpelt, gebastelt, gelernt und ausgetauscht. Es gibt Werkzeug, Komponenten, Lötkolben, Hardware und Netzwerkzubehör zum Basteln, Testen und Reparieren. Betrieben wird das technik.cafe von Privatleuten aus Leidenschaft, es gibt keinen Verein, keine Mitgliedschaft, keine Gebühren.",
    description_en: nil,
    external_url: "https://technik.cafe/",
    location: "Lörrach",
    rrule: "FREQ=MONTHLY",
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-ludwigsburg",
    title_de: "Chaostreff Ludwigsburg (DemoZ)",
    title_en: nil,
    description_de: "Der Chaostreff Ludwigsburg ist ein lockeres und offenes Zusammentreffen von Menschen, die sich dem CCC und der Hackerethik nahe fühlen. Wir treffen uns am letzten Donnerstag im Monat ab 18:00 Uhr im DemoZ in Ludwigsburg und ständig bei <a href=\"https://matrix.to/#/#chaostreff-lb:matrix.org\">Matrix</a>.",
    description_en: nil,
    external_url: "https://complb.de",
    location: "DemoZ, Ludwigsburg",
    rrule: "FREQ=MONTHLY;BYDAY=-1TH",
    start_time: "18:00",
    review: false
  },
  {
    slug: "chaostreff-luxemburg",
    title_de: "CCC Lëtzebuerg",
    title_en: nil,
    description_de: "Der Chaos Computer Club Lëtzebuerg trifft sich jeden Montag um 20 Uhr in der Hauptstadt Luxemburgs im Hackerspace ChaosStuff. Interessierte sind jederzeit herzlich willkommen, zu unseren Treffen zu kommen.",
    description_en: nil,
    external_url: "http://www.c3l.lu/",
    location: "Luxemburg",
    rrule: "FREQ=WEEKLY;BYDAY=MO",
    start_time: "20:00",
    review: false
  },
  {
    slug: "chaostreff-marburg",
    title_de: "Hackspace Marburg (hsmr)",
    title_en: nil,
    description_de: "Der Chaostreff Marburg findet jeden Montag ab 18:00 Uhr im <a href=\"https://hsmr.cc/\">Hackspace Marburg</a> statt. Aber auch sonst lohnt ein Besuch des [hsmr] immer. Erreichen könnt Ihr uns über die <a href=\"https://hsmr.cc/Infrastruktur/Mailinglisten\">Mailingliste</a> oder im IRC auf hackint #hsmr.",
    description_en: nil,
    external_url: "https://hsmr.cc/",
    location: "Marburg",
    rrule: "FREQ=WEEKLY;BYDAY=MO",
    start_time: "18:00",
    review: false
  },
  {
    slug: "chaostreff-markdorf",
    title_de: "Toolbox Bodensee e.V. Markdorf",
    title_en: nil,
    description_de: "Der Chaostreff Markdorf trifft sich regelmäßig im Hackerspace Toolbox Bodensee e. V. Alle galaktischen Wesen sind willkommen.",
    description_en: nil,
    external_url: "https://bodensee.space/chaostreff-markdorf",
    location: "Markdorf",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-muenster",
    title_de: "warpzone Münster",
    title_en: nil,
    description_de: "Das Chaos in Münster trifft sich jeden Mittwoch ab 19 Uhr in der warpzone, 51.943374° N, 7.638241° E.",
    description_en: nil,
    external_url: "http://www.warpzone.ms/",
    location: "Münster",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-neuss",
    title_de: "fnordeingang e.V. Neuss",
    title_en: nil,
    description_de: "Der Chaostreff Neuss findet jeden Mittwoch ab 19 Uhr in den Räumen des fnordeingang e. V. statt. Jeder ist herzlich willkommen, es wird keine Anmeldung benötigt.",
    description_en: nil,
    external_url: "https://fnordeingang.de/chaostreff",
    location: "Neuss",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-nuernberg",
    title_de: "Chaostreff Nürnberg",
    title_en: nil,
    description_de: "Der Chaostreff Nürnberg trifft sich abwechselnd im Hackerspace K4CG und Nerdberg.",
    description_en: nil,
    external_url: "https://chaostreff-nuernberg.de",
    location: "Nürnberg",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-osnabrueck",
    title_de: "Chaostreff Osnabrück",
    title_en: nil,
    description_de: "Der Chaostreff Osnabrück ist eine lockere Gruppe von Leuten mit Interesse in den Bereichen Sicherheit, Kryptographie, alternative Betriebssysteme, freie Software, Netzpolitik und vielen weiteren Themen. Interessierte sind jederzeit herzlich willkommen, zu unseren Treffen zu kommen.",
    description_en: nil,
    external_url: "https://chaostreff-osnabrueck.de/",
    location: "Osnabrück",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-potsdam",
    title_de: "Chaostreff Potsdam (machBar)",
    title_en: nil,
    description_de: "Der Chaostreff Potsdam trifft sich jeden Mittwoch um 19 Uhr. Die Treffen finden in den Räumen des Hackerspace machBar im freiLand, Friedrich-Engels-Straße 22, Haus 5 statt. Alle galaktischen Lebensformen sind willkommen.",
    description_en: nil,
    external_url: "https://www.ccc-p.org/",
    location: "Friedrich-Engels-Straße 22, Haus 5, Potsdam",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-rapperswil",
    title_de: "Coredump Rapperswil-Jona",
    title_en: nil,
    description_de: "(Fast) jeden Montag treffen wir uns ab 20 Uhr im <a href=\"https://www.coredump.ch/der-hackerspace/\">Hackerspace Coredump</a> auf dem Vinora-Areal in Jona (Schweiz) zur wöchentlichen „Hacknight". Wie bei all unseren Events sind Gäste dabei herzlich willkommen. Mit Ferienpass-Kursen und regelmäßigen Rust-Meetups engagiert sich der Verein Coredump auch in der Kinder- und Erwachsenen-Bildung.",
    description_en: nil,
    external_url: "https://www.coredump.ch/",
    location: "Vinora-Areal, Jona",
    rrule: "FREQ=WEEKLY;BYDAY=MO",
    start_time: "20:00",
    review: false
  },
  {
    slug: "chaostreff-recklinghausen",
    title_de: "Chaostreff Recklinghausen (Hackerhütte)",
    title_en: nil,
    description_de: "Jeden Mittwoch trifft sich der Chaostreff Recklinghausen in der Hackerhütte, Westcharweg 101, 45659 Recklinghausen.",
    description_en: nil,
    external_url: "http://c3re.de",
    location: "Westcharweg 101, 45659 Recklinghausen",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-regensburg",
    title_de: "Binary Kitchen Regensburg",
    title_en: nil,
    description_de: "Regensburg hackt in der <a href=\"http://binary.kitchen\">Binary Kitchen</a>. Immer montags. Offen für alle.",
    description_en: nil,
    external_url: "http://binary.kitchen",
    location: "Regensburg",
    rrule: "FREQ=WEEKLY;BYDAY=MO",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-rodgau",
    title_de: "Chaostreff Rodgau",
    title_en: nil,
    description_de: "Wir haben Anfang 2025 einen Chaostreff Rodgau gegründet. Wir treffen uns einmal im Monat an unterschiedlichen Orten. Termin und Ort werden auf unserer Website bekanntgegeben.",
    description_en: nil,
    external_url: "https://chaostreff-rodgau.codeberg.page",
    location: "Rodgau",
    rrule: "FREQ=MONTHLY",
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-rotterdam",
    title_de: "Chaostreff Rotterdam (Pixelbar)",
    title_en: "Chaostreff Rotterdam (Pixelbar)",
    description_de: "The Chaostreff of Rotterdam meets every Wednesdays around 20 Uhr at Pixelbar in the Keilewerf at the Vierhavensstraat 56 in Rotterdam close to RET / Metro station Marconiplein.",
    description_en: "The Chaostreff of Rotterdam meets every Wednesdays around 20 Uhr at Pixelbar in the Keilewerf at the Vierhavensstraat 56 in Rotterdam close to RET / Metro station Marconiplein.",
    external_url: "https://www.pixelbar.nl/contact/",
    location: "Vierhavensstraat 56, Rotterdam",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "20:00",
    review: false
  },
  {
    slug: "chaostreff-saarbruecken",
    title_de: "hacksaar Saarbrücken",
    title_en: nil,
    description_de: "Unser regelmäßiges Treffen findet jeden Mittwoch ab 19 Uhr im h´eck in der Rathausstraße 18 in 66125 Saarbrücken statt. Gäste und Interessierte sind immer gerne willkommen.",
    description_en: nil,
    external_url: "https://www.hacksaar.de",
    location: "Rathausstraße 18, 66125 Saarbrücken",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-schwerin",
    title_de: "Hacklabor Schwerin",
    title_en: nil,
    description_de: "Bist Du interessiert an Computerkrams, Programmieren, Capture-the-Flag-Challenges, 3D-Druckern, CO2-Lasern, Microcontrollern, Automatisierung, gesellschaftlichen Auswirkungen von Technik und Spaß am Gerät? Hat es Dich nach Mecklenburg-Vorpommern verschlagen? Dann komm ins Hacklabor in der Hagenower Straße 73, Schwerin. In unserer offenen Werkstatt findet sich vom Lötkolben bis zum 3D-Drucker alles, was das Makerherz höher schlagen lässt. Jugendlichen bieten wir im \"Jugend hackt Lab\" die Möglichkeit, Neues auszuprobieren und kreative Ideen zu verwirklichen. Unsere Treffen sind öffentlich und finden mittwochs und freitags ab 19 Uhr statt.",
    description_en: nil,
    external_url: "https://hacklabor.de/",
    location: "Hagenower Straße 73, Schwerin",
    rrule: "FREQ=WEEKLY;BYDAY=WE,FR",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-stralsund",
    title_de: "Port39 e.V. Stralsund (Chaostreff)",
    title_en: "Port39 e.V. Stralsund",
    description_de: "Das Chaos ist jetzt auch in Stralsund eingezogen! Als ein weiterer Space in Mecklenburg-Vorpommern möchten wir auch hier das gute Chaos verbreiten, mit Chaos macht Schule in Stralsund und Umgebung Jung und Alt für Technik und IT begeistern und mit diversen Projekten im Space mal mehr, mal weniger sinnvolle Dinge anstellen. Kommt gerne rum oder schaut auf unserer <a href=\"https://port39.de/\">Website</a> oder den Socials vorbei. Definitiv da sind wir jeden Donnerstag zum Chaostreff ab 19 Uhr und jeden 2. &amp; 4. Samstag ab 14 Uhr zum OpenSpace.",
    description_en: "As the first Erfa in Mecklenburg-Western Pomerania, we at Port39 e.V. make sure that there's a healthy dose of chaos in Stralsund. Feel free to drop by or check out our <a href=\"https://port39.de\">website</a>. We're definitely there every Thursday for the Chaos Meetup starting at 7pm and every 2nd &amp; 4th Saturday starting at 2pm for OpenSpace.",
    external_url: "https://port39.de/",
    location: "Stralsund",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-trier",
    title_de: "Maschinendeck e.V. Trier",
    title_en: nil,
    description_de: "Mit dem Maschinendeck e. V. haben wir uns zum Ziel gesetzt, in Trier einen Ort zu schaffen, wo alle Arten von Nerdkultur ein Zuhause finden können. Ob Du coden, löten, Kaffee rösten, Brettspiele spielen oder Deine neueste Verschwörungstheorie besprechen willst: Im Maschinendeck gibt es einen Platz für Dich. Das wöchentliche Treffen findet jeden Mittwoch, 20 Uhr, in unseren Räumen statt.",
    description_en: nil,
    external_url: "http://www.maschinendeck.org",
    location: "Trier",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "20:00",
    review: false
  },
  {
    slug: "chaostreff-tuebingen",
    title_de: "Chaostreff Tübingen",
    title_en: nil,
    description_de: "Der Chaostreff Tübingen ist eine lockere Sammlung zumeist Tübinger und Reutlinger Chaos. Wir treffen uns regelmäßig am letzten Sonntag im Monat gegen 18:00 Uhr im <a href=\"https://ki-maker.space/\">KIMS</a> und ungefähr jeden 2. Montag im Monat gegen 19:00 Uhr im <a href=\"https://www.fablab-neckar-alb.org/\">FabLab</a>. Beide Orte glücklicherweise gut zu Fuß vom Bahnhof erreichbar.",
    description_en: nil,
    external_url: "https://cttue.de",
    location: "Tübingen",
    rrule: "FREQ=MONTHLY;BYDAY=-1SU",
    start_time: "18:00",
    review: false
  },
  {
    slug: "chaostreff-villingen-schwenningen",
    title_de: "vspace.one Villingen-Schwenningen",
    title_en: nil,
    description_de: "Der Chaostreff Villingen-Schwenningen ist Treffpunkt für alle Chaosnahen aus dem Raum Schwarzwald-Baar. Er ist dem Maker- / Hackerspace vspace.one angeschlossen. Jeden Dienstag ab 19 Uhr finden öffentliche Treffen zur Wissensförderung in der Wilhelm-Binder-Straße 19 in Villingen statt. Für gemütliche Plätze, coole Atmosphäre und Mate ist gesorgt!",
    description_en: nil,
    external_url: "http://vspace.one",
    location: "Wilhelm-Binder-Straße 19, Villingen-Schwenningen",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "chaostreff-waldkraiburg",
    title_de: "Chaostreff Waldkraiburg",
    title_en: nil,
    description_de: "Der Chaostreff Waldkraiburg ist eine dem Chaos Computer Club zugehörige Gruppe und Anlaufstelle für alle chaosnahen und interessierten Wesen für die Landkreise Mühldorf am Inn, Altötting und darüber hinaus. Wir sind technikbegeisterte Menschen und beschäftigen uns mit IT-Sicherheit, Webdesign, Gaming, alternativen Betriebssystemen, Retrocomputing, freier Software, Netzpolitik und vielen weiteren Themen. Ob Anfänger oder Profi spielt keine Rolle, es ist keine Anmeldung erforderlich.",
    description_en: nil,
    external_url: "https://c3wkb.de",
    location: "Waldkraiburg",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "chaostreff-westerwald",
    title_de: "Westwoodlabs Westerwald",
    title_en: nil,
    description_de: "Der Chaostreff Westerwald trifft sich jeden Dienstag um 18 Uhr für alle Interessierten in den Räumen der Westwoodlabs in Ransbach-Baumbach.",
    description_en: nil,
    external_url: "https://westwoodlabs.de/",
    location: "Ransbach-Baumbach",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "18:00",
    review: false
  },
  {
    slug: "chaostreff-wuppertal",
    title_de: "Chaostreff Wuppertal (chaostal)",
    title_en: nil,
    description_de: "Der Chaostreff unter der Schwebebahn organisiert in regelmäßigen Abständen Treffen zum gegenseitigen Austausch. Neue Besucher sind jederzeit willkommen. Treffen finden jeden ersten Donnerstag im Monat ab 20 Uhr im Mirker Bahnhof, Mirker Straße 48, Wuppertal-Elberfeld statt. An allen anderen Donnerstagen wechselt der Ort.",
    description_en: nil,
    external_url: "https://www.chaostal.de/category/meeting",
    location: "Mirker Straße 48, Wuppertal-Elberfeld",
    rrule: "FREQ=MONTHLY;BYDAY=1TH",
    start_time: "20:00",
    review: false
  },
  {
    slug: "chaostreff-zwickau",
    title_de: "z-Labor Zwickau",
    title_en: nil,
    description_de: "Für alle chaosnahen Lebewesen öffnet das z-Labor donnerstags um 19 Uhr die Räumlichkeiten in der <a href=\"https://osm.org/go/0MCmr_jJo\">Kulturweberei</a> zum kollektiven Hacken, Basteln, Lernen und Philosophieren. Wir mögen Freie Software, IT-Sicherheit, (Analog-)Fotografie, 3D-Druck, Mate und viele Formen von (digitaler) Kunst. Neben Elektroniklabor und Rechentechnik gibt es eine Holz- und Metallwerkstatt, eine Musik-Ecke und einen Retro-Spiel-Bereich.",
    description_en: nil,
    external_url: "https://www.z-labor.space",
    location: "Kulturweberei, Zwickau",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "19:00",
    review: false
  }
]
