erfas = [
  {
    slug: "erfa-aachen",
    title_de: "CCC Aachen",
    title_en: "CCC Aachen",
    description_de: "Der CCC Aachen ist regelmäßig zu Themen- und offenen Abenden für Besucher*innen geöffnet. Unsere kleinen aber feinen Clubräume voller Plüschhaie liegen zwischen Hauptbahnhof und Stadtzentrum und sind aus beiden Richtungen in wenigen Minuten Fußweg zu erreichen (Schützenstraße 11, 52062 Aachen). Dank bunter LEDs sind sie besonders abends nicht zu übersehen.",
    description_en: "CCC Aachen opens its doors regularly to themed and open evenings. Our small but cozy space full of plush sharks is located within a few minutes by foot from central station and the city center (Schützenstraße 11, 52062 Aachen). Thanks to colorful LEDs it's especially easy to find at night.",
    external_url: "https://ccc.ac/",
    location: "Schützenstraße 11, 52062 Aachen",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-bamberg",
    title_de: "backspace e.V. Bamberg",
    title_en: "backspace e.V. Bamberg",
    description_de: "Der Bamberger Erfa-Kreis und Hackerspace ist der backspace e.V., ein Zusammenschluss von Menschen, die technische Grenzen überwinden wollen, Innovationen erproben und den freien Wissensaustausch befördern. Der backspace ist Thinktank, Werkstatt, Hackerspace, Freiraum, Zuhause, Labor und Impulsgeber. Es ist fast immer was los, besonders am Dienstag ab 19 Uhr im Spiegelgraben 41, 96052 Bamberg.",
    description_en: "The CCC affiliated hackerspace backspace gathers people interested in technical innovation and free information exchange. It is a think tank, workshop, hackerspace, open space, home, laboratory and instigator. There is something going on every day, but most people meet at Spiegelgraben 41 in Bamberg on Tuesday, 7pm.",
    external_url: "https://www.hackerspace-bamberg.de/",
    location: "Spiegelgraben 41, 96052 Bamberg",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-basel",
    title_de: "CCC Basel",
    title_en: "CCC Basel",
    description_de: "Die Türen des CCC Basel sind jeden Dienstagabend ab 19:30 Uhr geöffnet. Uns findet man an der Birsfelderstrasse 6 in CH-4132 Muttenz (Außentreppe zum Kellereingang). Falls du mit der Tram 14 vorfährst, empfehlen wir dir die Haltestelle Käppeli.",
    description_en: "CCC Basel opens its doors every Tuesday evening from 19:30. We are located at Birsfelderstrasse 6, 4132 Muttenz, Switzerland; just go down the outdoors stairway to the basement. If you arrive by public transit, we recommend taking tramway 14 to the stop Käppeli.",
    external_url: "https://ccc-basel.ch/",
    location: "Birsfelderstrasse 6, CH-4132 Muttenz",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:30",
    review: false
  },
  {
    slug: "erfa-berlin",
    title_de: "CCC Berlin – Club Discordia",
    title_en: "CCC Berlin – Club Discordia",
    description_de: "Der Club Discordia ist ein öffentliches Treffen in den Clubräumen des CCC Berlin (Marienstraße 11, 10117 Berlin-Mitte). Die Treffen finden jeden Dienstag und Donnerstag ab ca. 19 Uhr statt.",
    description_en: "Club Discordia is a public meeting located at the CCC Berlin (Marienstr. 11, 10117 Berlin-Mitte). Meetings are held every Thursday at 5pm.",
    external_url: "http://berlin.ccc.de/",
    location: "Marienstraße 11, 10117 Berlin",
    rrule: "FREQ=WEEKLY;BYDAY=TU,TH",
    start_time: "19:00",
    review: true
  },
  {
    slug: "erfa-bremen",
    title_de: "CCC Bremen",
    title_en: "CCC Bremen",
    description_de: "Ein öffentliches Treffen des CCC Bremen findet jeweils dienstags ab 20 Uhr in der Zweigstraße 1 statt.",
    description_en: "The public get together of CCC Bremen takes place every Tuesday at 8pm at Z1 (Zweigstraße 1, 28217 Bremen).",
    external_url: "https://www.ccchb.de/",
    location: "Zweigstraße 1, 28217 Bremen",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "20:00",
    review: false
  },
  {
    slug: "erfa-chemnitz",
    title_de: "CCC Chemnitz (ChCh)",
    title_en: nil,
    description_de: "Der Chaos Computer Club Chemnitz (ChCh) betreibt seit 2011 einen eigenen Hackspace in der Augustusburger Straße 102. Wir stehen allen technikinteressierten und kreativen Menschen offen und freuen uns immer über neue Gäste. Wir fühlen uns der Informationsfreiheit und der Aufklärung über die Auswirkungen aktueller Technologien auf die Gesellschaft verpflichtet. Trotzdem kommt bei uns auch der Spaß am Gerät nicht zu kurz.",
    description_en: nil,
    external_url: "https://chaoschemnitz.de",
    location: "Augustusburger Straße 102, Chemnitz",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "erfa-darmstadt",
    title_de: "CCC Darmstadt",
    title_en: "CCC Darmstadt",
    description_de: "Wir treffen uns jeden Dienstagabend ab 19 Uhr zum gemeinsamen Basteln, Diskutieren, Hacken, Nerden – eben einfach zum offenen Chaos – in unserem Hackspace in der Wilhelminenstraße 17, mitten in der Darmstädter Innenstadt. Aber auch an <a href=\"https://www.chaos-darmstadt.de/termine.html\">jedem anderen Abend</a> ist in der Regel etwas los. Neben der Nutzung unserer Elektronikwerkstatt hast du zum Beispiel die Möglichkeit, bei unserem <a href=\"https://www.chaos-darmstadt.de/wizardsofdos.html\">Capture-the-Flag-Team „Wizards of DoS"</a> reinzuschauen oder dich bei <a href=\"https://darmstadt.freifunk.net\">Freifunk Darmstadt</a> zu engagieren. Aktuelle Termine und Neuigkeiten sowie den Türstatus gibt's auf <a href=\"https://www.chaos-darmstadt.de/\">chaos-darmstadt.de</a>. Im IRC findest du uns unter <a href=\"https://webirc.hackint.org/#chaos-darmstadt\">#chaos-darmstadt auf hackint</a>. Mailingliste: public&lt;ät&gt;lists.darmstadt.ccc.de. Schau doch einfach mal vorbei!",
    description_en: "CCC Darmstadt meets Tuesdays from 8pm in their hackspace at Wilhelm-Leuschner-Strasse 36.",
    external_url: "https://www.chaos-darmstadt.de/",
    location: "Wilhelminenstraße 17, Darmstadt",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: true
  },
  {
    slug: "erfa-dortmund",
    title_de: "CCC Dortmund",
    title_en: nil,
    description_de: "Der Erfa Dortmund ist ein Treffen von Dortmundern oder Leuten, die in der Dortmunder Umgebung wohnen (Unna, Holzwickede, Schwerte etc.). Wem kreativer Umgang mit Technik nicht fremd ist, ist herzlich zum Treff im Langen August in der Braunschweiger Straße 22 in Dortmund eingeladen. Treffen finden dienstags und donnerstags ab 19 Uhr (+1h Chaos-Verspätung) statt.",
    description_en: nil,
    external_url: "http://www.chaostreff-dortmund.de",
    location: "Braunschweiger Straße 22, Dortmund",
    rrule: "FREQ=WEEKLY;BYDAY=TU,TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-dresden",
    title_de: "CCC Dresden (c3d2)",
    title_en: "CCC Dresden (c3d2)",
    description_de: "Die Chaoten aus dem ganzsächsischen bzw. südbrandenburgischen Raum treffen sich jeden Dienstag in Dresden (Details bitte jeweils <a href=\"http://www.c3d2.de/muc.html\">per Jabber unter c3d2@muc.hq.c3d2.de</a> erfragen). Darüberhinaus finden auch häufig, aber unregelmäßig Themenabende statt.",
    description_en: "The geeks from Saxony and southern Brandenburg meet every Tuesday in Dresden (<a href=\"http://www.c3d2.de/muc.html\">for details please ask via jabber at c3d2@muc.hq.c3d2.de</a>). Furthermore there are occasional get-togethers for specific subjects.",
    external_url: "http://www.c3d2.de/",
    location: "Dresden",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-duesseldorf",
    title_de: "Chaosdorf Düsseldorf",
    title_en: "Chaosdorf Düsseldorf",
    description_de: "Der Düsseldorfer Erfa (auch als Chaosdorf bekannt) betreibt einen Hackspace in der Sonnenstr. 58, der nahezu durchgehend geöffnet ist. Der Kennenlernabend, „Freitagsfoo", findet jeden Freitag ab 18 Uhr statt.",
    description_en: "CCC Düsseldorf (aka Chaosdorf) operates a hackspace in Sonnenstraße 58 that is open nearly 24/7. The best method for getting to know it is the \"Freitagsfoo\" event, taking place every Friday from 6pm.",
    external_url: "https://chaosdorf.de/",
    location: "Sonnenstraße 58, Düsseldorf",
    rrule: "FREQ=WEEKLY;BYDAY=FR",
    start_time: "18:00",
    review: false
  },
  {
    slug: "erfa-erlangen",
    title_de: "Bits'n'Bugs e.V. Erlangen",
    title_en: "Bits'n'Bugs e.V. Erlangen",
    description_de: "Der Bits'n'Bugs e.V. trifft sich jeden Freitag ab 18 Uhr im <a href=\"https://zam.haus/\">ZAM</a>, Hauptstr. 65-67, und zu weiteren unregelmäßigen Zeiten je nach Aktivitäten. Wir beteiligen uns außerdem regelmäßig an Veranstaltungen und Projekten des ZAM.",
    description_en: "Bits'n'Bugs e.V. meets every Tuesday at 7:30pm in E-Werk Erlangen, Fuchsenwiese 1, group room 5.",
    external_url: "http://erlangen.ccc.de/",
    location: "Hauptstraße 65-67, Erlangen",
    rrule: "FREQ=WEEKLY;BYDAY=FR",
    start_time: "18:00",
    review: true
  },
  {
    slug: "erfa-essen",
    title_de: "Chaospott Essen",
    title_en: "Chaospott Essen",
    description_de: "Der Chaospott ist die lokale Vertretung des CCC im Herzen des Ruhrgebiets. Wir treffen uns jeden Mittwoch ab 19 Uhr in der Sibyllastraße 9, 45136 Essen (Hofgebäude).",
    description_en: "Chaospott is the local subsidiary of the CCC at the heart of the Ruhr area. We meet every Wednesday at 7pm in the »foobar«.",
    external_url: "http://chaospott.de/",
    location: "Sibyllastraße 9, 45136 Essen",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: true
  },
  {
    slug: "erfa-flensburg",
    title_de: "CCC Flensburg",
    title_en: nil,
    description_de: "Deutschlands nördlichster Erfa trifft sich jeden Dienstag ab 18 Uhr in der Apenrader Straße 49, 24939 Flensburg. Bei unserem <a href=\"https://c3fl.de/mitmachen/openSpace/\">OpenSpace</a> sind neue Gesichter immer willkommen! Folgt uns gerne auch auf <a href=\"https://chaos.social/@chaos_fl\">Mastodon</a>.",
    description_en: nil,
    external_url: "https://c3fl.de/",
    location: "Apenrader Straße 49, 24939 Flensburg",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "18:00",
    review: false
  },
  {
    slug: "erfa-frankfurt",
    title_de: "CCC Frankfurt am Main",
    title_en: "CCC Frankfurt am Main",
    description_de: "Wir treffen uns jeden Dienstag und Donnerstag (auch an den meisten Feiertagen) ab 19 Uhr in unserem Hackerspace, dem HQ. Dazu sind alle Interessierten jederzeit herzlich eingeladen.",
    description_en: "We meet every Tuesday (even on most holidays) at 7pm in our hackspace the HQ. All interested people are welcome.",
    external_url: "http://ccc-ffm.de/hackerspace/",
    location: "Frankfurt am Main",
    rrule: "FREQ=WEEKLY;BYDAY=TU,TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-freiburg",
    title_de: "CCC Freiburg",
    title_en: "CCC Freiburg",
    description_de: "Der Chaos Computer Club Freiburg trifft sich montags und dienstags ab 19 Uhr sowie nach Lust und Laune in seinen Räumen in der Adlerstraße 12a, 79098 Freiburg. Plenum ist jede zweite Woche dienstags ab 20 Uhr.",
    description_en: "Erfa Freiburg meets on Tuesdays at 7pm in their own room at ArTik, the former underpass at Siegesdenkmal (Kaiser-Joseph-Strasse 141, 79089 Freiburg).",
    external_url: "http://cccfr.de",
    location: "Adlerstraße 12a, 79098 Freiburg",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: true
  },
  {
    slug: "erfa-fulda",
    title_de: "Magrathea Laboratories e.V. Fulda",
    title_en: nil,
    description_de: "Der Magrathea Laboratories e.V. (mag.lab) ist die lokale Chaosmanifestation und Treffpunkt einiger Haecksen, Hacker und anderweitig Technikinteressierter in der Lindenstraße 14 in Fulda. Das Chaos steht allen immer freitags ab 19 Uhr offen.",
    description_en: nil,
    external_url: "https://maglab.space/",
    location: "Lindenstraße 14, Fulda",
    rrule: "FREQ=WEEKLY;BYDAY=FR",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-goettingen",
    title_de: "CCC Göttingen",
    title_en: "CCC Göttingen",
    description_de: "Der Erfa-Kreis Göttingen wurde im November 2007 von Hackern gegründet, die sich dem Chaos Computer Club nahefühlen. Open Chaos findet jeden zweiten Dienstag ab 20 Uhr im Neotopia (Von-Bar-Straße 2-4, Keller des MLP-Hauses) statt. Interessierte sind herzlich willkommen.",
    description_en: "Erfa Göttingen was founded Nov 2007 by hackers close to the Chaos Computer Club. Open Chaos is every Tuesday from 8pm at NOKLAB (Neustadt 7, Innenstadt). All interested people are welcome.",
    external_url: "http://www.chaostreff-goettingen.de/",
    location: "Von-Bar-Straße 2-4, Göttingen",
    rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=TU",
    start_time: "20:00",
    review: true
  },
  {
    slug: "erfa-hamburg",
    title_de: "CCC Hamburg",
    title_en: "CCC Hamburg",
    description_de: "Der Hamburger Erfa-Kreis trifft sich in der Viktoria-Kaserne (1. Stock, Ostflügel), Zeiseweg 9, 22765 Hamburg. Der zweite Freitag und der letzte Dienstag im Monat sind perfekt zum Kennenlernen und Fragen stellen, weitere Termine finden sich auf dem <a href=\"https://www.hamburg.ccc.de/calendar/\">Kalender des Erfa Hamburg</a>, der mit öffentlichen Veranstaltungen gefüllt ist.",
    description_en: "The Erfakreis Hamburg meets at Viktoria-Kaserne, room 119 (1st floor, east wing) Zeiseweg 9, 22765 Hamburg. Every second Friday and last Tuesday of the month are great opportunities to meet people and ask questions. We also have a <a href=\"http://www.hamburg.ccc.de/category/termine\">calendar</a> filled with events open for visitors.",
    external_url: "http://hamburg.ccc.de/",
    location: "Zeiseweg 9, 22765 Hamburg",
    rrule: "FREQ=MONTHLY;BYDAY=2FR",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-hannover",
    title_de: "CCC Hannover",
    title_en: "CCC Hannover",
    description_de: "Das regionale Chaos in Hannover trifft sich jeden Mittwoch ab 19 Uhr in der Bürgerschule im Clubraum (Raum 3.1) im Stadtteilzentrum Nordstadt.",
    description_en: "The regional Chaos in Hannover meets every second Wednesday of the month from 8pm and on the last Sunday of the month from 4pm at the Bürgerschule in their clubroom (room 3.1) in the community center Nordstadt.",
    external_url: "https://hannover.ccc.de/",
    location: "Bürgerschule, Raum 3.1, Hannover",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: true
  },
  {
    slug: "erfa-kaiserslautern",
    title_de: "Chaos inKL. e.V. Kaiserslautern",
    title_en: nil,
    description_de: "Der Chaos inKL. e.V. ist die Kaiserslauterner Niederlassung des Chaos Computer Clubs. Unsere öffentlichen Veranstaltungen sind die Hacknight (der samstägliche Basteltreff ab 19 Uhr), das monatliche Seminar und das monatliche Kneipentreffen.",
    description_en: nil,
    external_url: "http://www.chaos-inkl.de/",
    location: "Kaiserslautern",
    rrule: "FREQ=WEEKLY;BYDAY=SA",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-karlsruhe",
    title_de: "Entropia e.V. Karlsruhe",
    title_en: "Entropia e.V. Karlsruhe",
    description_de: "Der <a href=\"https://entropia.de/\">Erfa-Kreis Karlsruhe</a> ist ein eingetragener Verein mit dem Namen Entropia. Die öffentlichen <a href=\"https://entropia.de/Treffen\">Treffen</a> finden jeden Samstag ab 19:30 Uhr in <a href=\"https://entropia.de/Clubr%C3%A4ume\">den Räumen des Erfa Karlsruhe</a> (Gewerbehof, Steinstraße 23) statt und richten sich an alle aus Karlsruhe und dem Umland.",
    description_en: "Erfa Karlsruhe is a registered club with the name 'Entropia'. The public meetings take place every Sunday from 7:30pm at our club (Gewerbehof, Steinstr. 23) and targets people from Karlsruhe and surrounding region.",
    external_url: "https://entropia.de/",
    location: "Steinstraße 23, Karlsruhe",
    rrule: "FREQ=WEEKLY;BYDAY=SA",
    start_time: "19:30",
    review: true
  },
  {
    slug: "erfa-kassel",
    title_de: "flipdot e.V. Kassel",
    title_en: "flipdot e.V. Kassel",
    description_de: "flipdot e.V. hackerspace kassel ist der lokale Erfa-Kreis – ein lebendiger Ort mit viel Platz zum Bausteln und Coden. Es gibt gut ausgestattete Werkstatträume, Vortrags- und Kinoraum und eine Küche mit Profi-Pizzaofen. Im flipdot wird sehr oft zusammen gekocht und gegessen. flipdot ist seit 2009 Brutstätte neuer Ideen, Wohnzimmer, anarchistische Volkshochschule, Coder-Cave und umtriebige Werkstatt. Offen für Besucher jeden Dienstag ab 19 Uhr, Schillerstraße 25, 34117 Kassel.",
    description_en: "flipdot e.V. hackerspace kassel is the local Erfa circle – a lively place with plenty of space for building and coding. There are well-equipped workshop rooms, a lecture and cinema room, and a kitchen with a professional pizza oven. At flipdot, people often cook and eat together. Since 2009, flipdot has been a breeding ground for new ideas, a living room, an anarchist adult education center, a coder's cave, and a bustling workshop. Open to visitors every Tuesday from 7pm, Schillerstraße 25, 34117 Kassel.",
    external_url: "http://kassel.ccc.de/",
    location: "Schillerstraße 25, 34117 Kassel",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-koeln",
    title_de: "c4 Köln",
    title_en: "c4 Cologne",
    description_de: "Der c4 ist der westliche Brückenkopf des innovativen Technologieeinsatzes mit allen Features, die zum Chaos gehören. Öffentliche Treffen gibt es jeden Donnerstag ab 19:30 Uhr im Chaoslabor in Köln-Ehrenfeld, an jedem letzten Donnerstag im Monat gibt es ein OpenChaos als Vortragsrahmenprogramm.",
    description_en: "The c4 is a westward bridge head of the innovative technology usage with all features that are necessary for chaos. The public meeting is called OpenChaos and takes place on the last Thursday of the month at 19:30 in the Chaoslabor in Cologne-Ehrenfeld.",
    external_url: "http://koeln.ccc.de/",
    location: "Köln-Ehrenfeld",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "19:30",
    review: false
  },
  {
    slug: "erfa-leipzig",
    title_de: "dezentrale e.V. Leipzig",
    title_en: nil,
    description_de: "Der dezentrale e.V. vertritt als Erfa das lokale Chaos in Leipzig. Wir bieten einen Anlaufpunkt für Softwarenerds, Künstler:innen, Hardwareschraubende und -löter:innen und alle chaosnahen Themen. Infos über uns findest Du unter <a href=\"http://dezentrale.space\">dezentrale.space</a>. Unser Vernetzungsabend ist der Chaostreff jeden Freitag ab 19:00.",
    description_en: nil,
    external_url: "http://dezentrale.space",
    location: "Leipzig",
    rrule: "FREQ=WEEKLY;BYDAY=FR",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-luebeck",
    title_de: "Chaotikum e.V. Lübeck",
    title_en: "Chaotikum e.V. Lübeck",
    description_de: "Der Lübecker Erfa ist der Chaotikum e.V., welcher seit 2012 den Hackspace Nobreakspace betreibt. Dort treffen sich seitdem technikinteressierte Menschen, um an diversen Projekten zu arbeiten, über Themen zu reden, die uns beschäftigen, und vor allem um Spaß zu haben. Open Space ist immer Mittwochs ab 19:00 Uhr.",
    description_en: "The Lübeck Hackspace group is Chaotikum e.V., which has been running the Nobreakspace hackspace since 2012. Since then, tech enthusiasts have been meeting there to work on various projects, discuss topics that interest them, and above all, have fun. Open Space is every Wednesday from 7:00 PM.",
    external_url: "https://chaotikum.org",
    location: "Lübeck",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-mainz-wiesbaden",
    title_de: "CCC Mainz/Wiesbaden",
    title_en: "CCC Mainz/Wiesbaden",
    description_de: "Das Wiesbadener Chaos trifft sich jeden Dienstag ab 19 Uhr in seinen Räumen am Sedanplatz 7 in Wiesbaden. Die Treffen richten sich an alle aus Mainz/Wiesbaden und dem nahen Umland.",
    description_en: "The Chaos Computer Club Mainz meets every Tuesday, 7pm, at Sedanplatz 7 in Wiesbaden. The meetup is addressed to everyone from Mainz/Wiesbaden and the near surroundings.",
    external_url: "http://www.cccmz.de",
    location: "Sedanplatz 7, Wiesbaden",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-mannheim",
    title_de: "CCC Mannheim",
    title_en: "CCC Mannheim",
    description_de: "Der Erfa-Kreis Mannheim ist eine Anlaufstelle für Computer- und Technikinteressierte, die Gleichgesinnte suchen. Hier kann man sich austauschen, seine Ideen präsentieren und diskutieren. Unsere öffentlichen Treffen finden jeden Freitag ab 19 Uhr statt. Die Termine stehen in unserem Wiki.",
    description_en: "Erfa Mannheim is a local contact point for people that are interested in computer and technology, who search for like minded people. You can exchange, present and discuss your ideas. Our public meeting takes place every Friday.",
    external_url: "http://www.ccc-mannheim.de",
    location: "Mannheim",
    rrule: "FREQ=WEEKLY;BYDAY=FR",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-muenchen",
    title_de: "µC³ München",
    title_en: "µC³ Munich",
    description_de: "Die öffentlichen Treffen des µC³ finden am zweiten Dienstag jeden Monats ab ca. 20 Uhr im Club in der Schleißheimer Straße 39 (Ecke Heßstraße 90) statt. Dies ist natürlich auch ein Ort, um jederzeit mit jemandem des Münchner CCCs ins Gespräch zu kommen.",
    description_en: "The public meetup of the µC³ takes places every second Tuesday of the month, starting at about 8pm at Schleißheimer Str. 39 (corner to Heßstraße 90).",
    external_url: "https://muc.ccc.de/",
    location: "Schleißheimer Straße 39, München",
    rrule: "FREQ=MONTHLY;BYDAY=2TU",
    start_time: "20:00",
    review: false
  },
  {
    slug: "erfa-offenburg",
    title_de: "Section77 e.V. Offenburg",
    title_en: nil,
    description_de: "Der lockere Treff von Section77 e. V. für alle Chaos-Interessierten aus dem Raum Offenburg findet jeden Dienstag ab 20 Uhr im Hackspace statt. Dieser befindet sich in der Hauptstraße 1 in Offenburg (direkt im Bahnhofsgebäude). Gäste sind immer willkommen.",
    description_en: nil,
    external_url: "https://section77.de",
    location: "Hauptstraße 1, Offenburg",
    rrule: "FREQ=WEEKLY;BYDAY=TU",
    start_time: "20:00",
    review: false
  },
  {
    slug: "erfa-paderborn",
    title_de: "CCC Paderborn (subraum)",
    title_en: "CCC Paderborn",
    description_de: "Wir treffen uns immer mittwochs in unserem Hackerspace \"subraum\" in der Westernmauer 12-16.",
    description_en: "We meet up Wednesdays at the pottery in the \"Kulturwerkstatt\". Our move to our new rooms in Westernmauer 12 is imminent.",
    external_url: "https://www.c3pb.de/",
    location: "Westernmauer 12-16, Paderborn",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: true
  },
  {
    slug: "erfa-salzburg",
    title_de: "Erfa Salzburg",
    title_en: nil,
    description_de: "Der Erfa Salzburg ist eine als eingetragener Verein organisierte und trotzdem lockere Runde von Leuten, die sich mit dem Chaos Computer Club e.V. eng verbunden fühlen. Wir versuchen, einen Blick hinter die Kulissen zu werfen und viele Dinge zu hinterfragen und zu diskutieren.",
    description_en: nil,
    external_url: "http://sbg.chaostreff.at/",
    location: "Salzburg",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "erfa-siegen",
    title_de: "Chaos Siegen",
    title_en: nil,
    description_de: "Chaos Siegen besteht aus einer Handvoll freundlicher und offener Menschen mit einer Leidenschaft für Netzpolitik, dem Chaos Computer Club im Hintergrund und gestrandet im Hackspace Siegen durch die Wirren unserer Galaxie. #tuwat und komm vorbei!",
    description_en: nil,
    external_url: "https://c3si.de/",
    location: "Siegen",
    rrule: nil,
    start_time: nil,
    review: false
  },
  {
    slug: "erfa-stralsund",
    title_de: "Port39 e.V. Stralsund",
    title_en: "Port39 e.V. Stralsund",
    description_de: "Als erster Erfa in Mecklenburg-Vorpommern sorgen wir als Port39 e.V. in Stralsund und Umgebung für eine ordentliche Portion Chaos. Mit Chaos macht Schule, Vorträgen und Workshops, Hacking-Sessions, Löt-Workshops, RepairCafés und vielem mehr wollen wir Jung und Alt für Technik, IT und allem, was dazu gehört, begeistern, und mit diversen Projekten im eigenen Hackerspace mal mehr, mal weniger sinnvolle Dinge anstellen. Kommt gerne rum oder schaut auf unserer <a href=\"https://port39.de\">Website</a> oder auf <a href=\"https://chaos.social/@Port39\">Mastodon</a> vorbei. Definitiv da sind wir jeden Donnerstag zum Chaostreff ab 19 Uhr und jeden 2. &amp; 4. Samstag ab 14 Uhr zum OpenSpace.",
    description_en: "As the first Erfa in Mecklenburg-Western Pomerania, we at Port39 e.V. make sure that there's a healthy dose of chaos in Stralsund and the surrounding area. Through \"Chaos macht Schule\" events, lectures, workshops, hacking sessions, soldering workshops, Repair Cafés, and much more, we aim to inspire people of all ages to get excited about technology, IT, and everything that goes with it. Feel free to drop by or check out our <a href=\"https://port39.de\">website</a> or <a href=\"https://chaos.social/@Port39\">Mastodon</a>. We're definitely there every Thursday for the Chaos Meetup starting at 7pm and every 2nd &amp; 4th Saturday starting at 2pm for OpenSpace.",
    external_url: "https://port39.de",
    location: "Stralsund",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-stuttgart",
    title_de: "CCC Stuttgart",
    title_en: "CCC Stuttgart",
    description_de: "Der Chaos Computer Club Stuttgart e.V. trifft sich jeden ersten Dienstag im Monat im Lichtblick in der Stadtmitte (Reinsburgstraße 13) ab 18:30 Uhr und jeden dritten Mittwoch im Monat im Shackspace (Ulmer Straße 255) ab 18:30 Uhr. Im Shackspace kann Bastelhardware gerne mitgebracht werden. Jeden zweiten Donnerstag im Monat haben wir unsere Vortragsreihe in der Stadtbibliothek Stuttgart am Mailänder Platz.",
    description_en: "Der Chaos Computer Club Stuttgart e.V. meets every first Tuesday of the month at the Zadu-Bar (Reuchlinstraße 4b) at 6:30pm and every third Wednesday of the month at the Shackspace (Ulmer Straße 255). Our monthly Talk is every second Thursday of the month in the public library of Stuttgart at the Mailänder Platz at 7:30pm.",
    external_url: "https://www.cccs.de/",
    location: "Stuttgart",
    rrule: "FREQ=MONTHLY;BYDAY=1TU",
    start_time: "18:30",
    review: true
  },
  {
    slug: "erfa-ulm",
    title_de: "Chaostreff Ulm",
    title_en: "Chaostreff Ulm",
    description_de: "Der Chaostreff Ulm findet jeden Montag ab 19:30 Uhr im Café Einstein an der Uni Ulm statt, außer jeden zweiten Montag des Monats. Dieser ist dem Chaosseminar vorbehalten.",
    description_en: "The Chaostreff Ulm takes place every Monday at 8:00pm in the Freiraum (3rd floor, Platzgasse 18, Ulm) at Hackerspace Ulm e.V. In addition, the talk series Chaos seminar on various topics is held there every second Monday of the month.",
    external_url: "http://www.ulm.ccc.de/",
    location: "Café Einstein, Uni Ulm",
    rrule: "FREQ=WEEKLY;BYDAY=MO",
    start_time: "19:30",
    review: true
  },
  {
    slug: "erfa-unna",
    title_de: "CCC Unna (UN-Hack-Bar)",
    title_en: "CCC Unna (UN-Hack-Bar)",
    description_de: "Der CCC Unna trifft sich für gewöhnlich jeden Donnerstag ab ca. 19 Uhr in den Räumen der UN-Hack-Bar. Dort quatschen wir über allerlei Dinge wie z. B. Netzpolitik, Politik im Allgemeinen, Computer &amp; Technik, aber auch schonmal darüber, wie man einen brennenden Feuerlöscher löscht oder das neueste Internet-Meme. ;-) Natürlich wird auch gebastelt, gebaut und im besten Sinne gehackt. Gäste aller Couleur sind gern gesehen.",
    description_en: "The CCC Unna usually meets every Thursday at around 7pm in the rooms of the UN-Hack-Bar. We chat about all kinds of topics: from net politics and politics in general to computers and technology, and sometimes even about odd questions like how to extinguish a burning fire extinguisher or the latest internet meme. ;-) Of course, we also tinker, build, and hack things in the best possible sense. Guests of all kinds are very welcome.",
    external_url: "https://www.un-hack-bar.de/ccc-unna/",
    location: "Unna",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-wien",
    title_de: "CCC Wien",
    title_en: "CCC Vienna",
    description_de: "Der Chaos Computer Club Wien trifft sich einmal im Monat, meistens im <a href=\"https://metalab.at/\">Metalab</a>. Details zu den Treffen werden <a href=\"https://c3w.at/events/\">auf der Webseite des C3W</a> bekanntgegeben. Für Fragen und allgemeine Announcements stehen die <a href=\"https://c3w.at/mitmachen/\">öffentliche C3W-Mailingliste</a> oder <a href=\"https://chaos.social/@C3Wien\">@C3Wien@chaos.social</a> bereit. Komm vorbei!",
    description_en: "The Chaos Computer Club Vienna meets once a month. Usually at <a href=\"https://metalab.at/\">Metalab</a>. Find details on <a href=\"https://c3w.at/events/\">our website</a>. Use the <a href=\"https://c3w.at/mitmachen/\">public mailinglist</a> or <a href=\"https://chaos.social/@C3Wien\">@C3Wien@chaos.social</a> to ask questions or to receive announcements. Come by!",
    external_url: "https://c3w.at/",
    location: "Metalab, Wien",
    rrule: "FREQ=MONTHLY",
    start_time: "19:00",
    review: false
  },
  {
    slug: "erfa-wuerzburg",
    title_de: "Nerd2Nerd Würzburg",
    title_en: nil,
    description_de: "Nerd2Nerd trifft sich jeden Donnerstag ab 18 Uhr im FabLab Würzburg.",
    description_en: nil,
    external_url: "http://nerd2nerd.org/",
    location: "FabLab Würzburg",
    rrule: "FREQ=WEEKLY;BYDAY=TH",
    start_time: "18:00",
    review: false
  },
  {
    slug: "erfa-zuerich",
    title_de: "CCCZH Zürich",
    title_en: "CCCZH Zurich",
    description_de: "Der CCCZH ist Teil des Hackerspace <a href=\"https://www.bitwaescherei.ch/\">bitwäscherei</a>. Von Züri Hardbrücke aus einen halben Katzensprung in die Zentralwäscherei Zürich an der Neuen Hard 12.",
    description_en: "The Chaostreff Zurich meets every Wednesday from 7pm at the Hackerspace at Luegislandstrasse 485 in Zürich/Schwamendingen.",
    external_url: "https://www.ccczh.ch/",
    location: "Neue Hard 12, Zürich",
    rrule: "FREQ=WEEKLY;BYDAY=WE",
    start_time: "19:00",
    review: true
  }
]
